### PR TITLE
Mouse improvements

### PR DESCRIPTION
**Pull request by ehmry**

### CODE REVIEW

**Comment by twinaphex** [comment]
OK, regarding mmap, it might be prudent to come up with a HAVE_MMAP ifdef since some targets such as game consoles might not have mmap support at all. Or will dynarecs simply not be compiled in for those targets? If so, we might be able to do without ifdefs then.

**Comment by ehmry** [comment]
Mmap has been in POSIX since 1992, so I would think it would be ubiquitous, but I could be wrong.

**Comment by ehmry** [comment]
TIL. Now with HAVE_MMAP.

**Comment by twinaphex** [comment]
OK, thanks.

**Pull request merged**
